### PR TITLE
Help on fixing tests for Feature/boto3

### PR DESCRIPTION
**Pull request by trecouvr**
Using this PR to launch travis tests. Work should be merged into main PR : https://github.com/django-ses/django-ses/pull/183

### CODE REVIEW

**Comment by pcraciunoiu** [comment]
Thanks for helping @trecouvr Looks like tests still fail.

@hmarr could you make me an admin? Should be here: https://github.com/orgs/django-ses/people

I was thinking to add @trecouvr and @GitRon as contributors so they can share work on a PR to do this upgrade. But I don't seem to have permissions to do that.

**Comment by pcraciunoiu** [comment]
@trecouvr I was able to add you as outside collaborators for now. Maybe you can work with @GitRon to consolidate this into one PR, pushing to this repo.

**Comment by hmarr** [comment]
I've made you an org owner @pcraciunoiu 👍

**Comment by GitRon** [comment]
@trecouvr I merged your test fixes in my branch, so we can close this PR, right? Thanks again! 👍 👍

**Comment by trecouvr** [comment]
@pcraciunoiu When I click on the invitation link you sent me I get an error, maybe I already accepted it? Do you know how can I see if I have accepted it or not?

And yes, we can close this one once the gitron pr is green.

**Comment by trecouvr** [comment]
Good to go on https://github.com/django-ses/django-ses/pull/183

**Pull request closed without merging**
