### PR TITLE
Add default_auto_field to apps.py

### LINKED ISSUE #230: default_auto_field needs to be set in apps.py
Django 3.2 introduced the ability to set the default auto key type used on models: https://docs.djangoproject.com/en/3.2/releases/3.2/#customizing-type-of-auto-created-primary-keys

With this change, you can globally set `DEFAULT_AUTO_FIELD` in your application and all models using `AutoField` will use the specified type. Individual apps can set their own auto field type by setting `default_auto_field` in their `apps.py`.

Without `default_auto_field` being set in `apps.py`, you receive this message when generating migrations:

```
django_ses.SESStat: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the DjangoSESConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'
```

What's worse however, is that Django will also attempt to create a new migration to update the `id` field for `SESStat` to whatever your application's `DEFAULT_AUTO_FIELD` is set to. This attempts to create a new migration wherever `django-ses` is installed which may not be writable by the application.

The fix for this is simply to set `default_auto_field` in `apps.py`.

### PR DESCRIPTION
**Pull request by AndrewGuenther**
Fixes #230

### CODE REVIEW

**Review by pcraciunoiu — APPROVED** [review]
Looks good to me.

@AndrewGuenther are you able to install your fork and test it manually to confirm this fixes the issue?

**Comment by AndrewGuenther** [comment]
Yep! I confirmed it works.

**Comment by pcraciunoiu** [comment]
Released in 2.3.1 https://pypi.org/project/django-ses/2.3.1/

**Comment by AndrewGuenther** [comment]
Thanks!

**Pull request merged**
