### PR TITLE
Issue #322 AWS Session Integration

### PR DESCRIPTION
**Pull request by SaiVenkatDhulipudi**
- References:
- https://docs.aws.amazon.com/cli/v1/userguide/cli-configure-files.html
- https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html

### CODE REVIEW

**Comment by pcraciunoiu** [comment]
Thanks @SaiVenkatDhulipudi this is going to be too difficult to review with all the lint changes.

Is there any way you can revert those, and put them in a separate PR?

**Comment by SaiVenkatDhulipudi** [comment]
Updated the PR...could you please check now...?

**Comment by pcraciunoiu** [comment]
There are still a few files that have lint changes. If it's not too time consuming, please revert those too. I will review later this week either way.

**Comment by SaiVenkatDhulipudi** [comment]
> There are still a few files that have lint changes. If it's not too time consuming, please revert those too. I will review later this week either way.

I will raise  a pr with linting added first then raise a pr for session authentication
hope that works...

**Comment by SaiVenkatDhulipudi** [comment]
I have updated the pr, Could you please review this

**Comment by pcraciunoiu** [comment]
@SaiVenkatDhulipudi were you able to test this manually using

1. the previous configuration options, without session profile
2. the new session profile setting

I just want to make sure both worked for you.

Code changes look good to me.

**Comment by SaiVenkatDhulipudi** [comment]
@pcraciunoiu  Yes both worked for me...

**Review by pcraciunoiu — COMMENTED** [review]
:+1:

**Comment by pcraciunoiu** [comment]
Released in v4.1.0 - https://pypi.org/project/django-ses/4.1.0/

**Pull request merged**
