### PR TITLE
Add test coverage for Django 4.0

### PR DESCRIPTION
**Pull request by GitRon**
Added django 4.0 to text matrix

### CODE REVIEW

**Comment by GitRon** [comment]
Hi @pcraciunoiu - I added django 4.0 to our test pipeline and updated the docs. Removed the apparently deprecated travis file as well.

**Comment by GitRon** [comment]
@pcraciunoiu Sorry for the many commits, I squashed them now to a single one.

**Comment by pcraciunoiu** [comment]
Thanks @GitRon I uploaded this to pypi as v2.6.0 - https://pypi.org/project/django-ses/2.6.0/

**Comment by GitRon** [comment]
@pcraciunoiu Awesome, thx for the quick action!

**Pull request merged**
