### PR TITLE
Fixed syntax error with Python 3.4.3

### PR DESCRIPTION
**Pull request by Zeioth**
I tried to install django-ses and I recieved a syntax error so i solved it. 
Also, it would be a good idea to add a new tag for the version 0.8.0 soon.
Regards.

EDIT: I can see you don't have much time. If you want, add me as mantainer, so i can help and accept push requests. Thank you.

### CODE REVIEW

**Comment by delikat** [comment]
+1, would be q chill if this could be merged

**Comment by graup** [comment]
+1, as it is django-ses is incompatible with Python 3.4.3 / 3.5.

**Comment by graup** [comment]
Actually this seems to be invalid syntax in 3.5?

**Comment by mwharrison** [comment]
:+1: @graup is correct though, this change is throwing a syntax error on 3.5

**Comment by pcraciunoiu** [comment]
Pip install worked fine for me in 3.4.3. And if run python 3.4.3 locally, this works:

```
try:
    stuff
except Exception as e:
    print('e', e)
```

**Comment by pcraciunoiu** [comment]
Closing. Please reopen with updated PR if this is still an issue.

**Pull request closed without merging**
