### PR TITLE
Ported to Python3

### PR DESCRIPTION
**Pull request by Zeioth**
If you preffer merge my fork or create a new repository for Python 3 it's up to you. If you find some error (you shouln't) please send me a private message.

### CODE REVIEW

**Comment by troygrosfield** [comment]
Changes seem simple enough.  @hmarr, any reason this can't be merged?

**Comment by Zeioth** [comment]
I'm not sure if the project is still mantained. I'll upload it later as django-ses-python3.

**Comment by troygrosfield** [comment]
I would be awesome to just transfer ownership of this repo since it already has the correct pypi name. Having so many different flavors of "django-ses-*" is quite annoying:

- https://pypi.python.org/pypi/django-ses
- https://pypi.python.org/pypi/django-ses-backend
- django-ses-python3

It would be nice to make the project community owned and moved to it's own repo at:

- https://github.com/django-ses/django-ses

That way we don't need to keep going through this flow of projects losing maintainers which will always continue to happen.  

@hmarr, any chance you can move this app as suggested above if you're no longer maintaining?  Then add other repo owners such as @Zeioth who has already made the necessary changing to port to python 3.

**Comment by troygrosfield** [comment]
@pcraciunoiu, just saw the note on the readme about maintainers.  Can to elaborate on the convo above?

**Comment by pcraciunoiu** [comment]
I'm happy to grant someone access if they are interested in being an active maintainer.

**Comment by pcraciunoiu** [comment]
Although looking at it, I don't seem to have permission to do that.

**Comment by troygrosfield** [comment]
I send @hmarr an email since he'd likely have to be the person to do all this.  We'll see what he says...

**Comment by troygrosfield** [comment]
@Zeioth, would you want to be a maintainer for this project?

**Comment by hmarr** [comment]
Sorry for the radio silence - just got back from vacation.

I've moved this project to the django-ses organisation, and invited @Zeioth plus the other previous maintainers (@pcraciunoiu and @tswicegood).

@troygrosfield if you're interested in helping out, let me know and I'll ping you over an invite.

**Comment by troygrosfield** [comment]
@hmarr, Thanks for doing that as it would be nice to see this project live on for the interested parties!

I don't mind taking a back seat and issuing PRs when needed as long as the current maintainers are ok maintaining. I feel it may be best not to have too many hands in the pot at once. However, if the current maintainers + @Zeioth choose to not continue to maintain, then I'll step in.

**Comment by pcraciunoiu** [comment]
I can be backup in some cases, and certainly grant people access, etc, but I'm not realistically going to maintain.

**Comment by troygrosfield** [comment]
@hmarr, feel free to add me as a maintainer.

**Comment by hmarr** [comment]
@troygrosfield - done.

**Comment by troygrosfield** [comment]
Also, who all has permissions to release to pypi?  Feel free to add me there if others aren't planning on doing any releases.

**Comment by troygrosfield** [comment]
@hmarr, I joined the org, but still need to be added a collaborator to this project to be able to merge PRs.

**Comment by hmarr** [comment]
Doh, I hadn't added the repo to the team. Should be fixed now.

**Comment by troygrosfield** [comment]
:+1:  Works.  Thanks!

**Comment by Zeioth** [comment]
My computer died, i'm back. Nice to see master branch working again. About being maintainer, i can give a hand, just like now, but i don't consider myself experienced enough to be the main maintainer yet. I didn't receive your invitation, resend if you need me. Glad to help.

**Pull request merged**
